### ISSUE TITLE
SQL Injection still happens despite of using prepare statement already

### ISSUE THREAD

**Issue by duongcao-ea** [nghiant3223/handbook#2]
![Untitled](https://user-images.githubusercontent.com/85658550/177800940-8b30a2a7-ee24-4a78-b48a-cc5824134647.png)
Can anyone understand the explanation `This also shows that a prepared statement can still be vulnerable to SQL injection if the data is concatenated. Because in the vulnerable example it was already a prepared statement that was used.`?
Link to the post: https://www.vaadata.com/blog/how-to-strengthen-the-security-of-your-apis-to-counter-the-most-common-attacks/
Thanks!

**Comment by nghiant3223** [comment]
SQL injection doesn't happen in the code block you captured above. 
It does happen in [this](https://www.vaadata.com/blog/how-to-strengthen-the-security-of-your-apis-to-counter-the-most-common-attacks/#:~:text=vulnerable%20PHP%20code%3A-,%3C%3Fphp%0A%0Atry%7B%0A%20%20%20%20%24db%20%3D%20new%20PDO(%27sqlite%3Adatabase/base.sqlite3%27)%3B%0A%20%20%20%20%24db%2D%3EsetAttribute(PDO,Content%2DType%3A%20application/json%3B%20charset%3Dutf%2D8%27)%3B%0Aecho%20json_encode(%24recipes%2C%20JSON_PRETTY_PRINT)%3B,-As%20we%20can) example, where concatenation is used rather than `?`!

**Comment by duongcao-ea** [comment]
Got it. Thanks!
